version: '3'
services:
  solrcloud:
    build: solrcloud
    image: solrcloud
    ports:
    - "127.0.0.1:8983:8983"
    - "127.0.0.1:2181:2181"
    volumes:
    - ./sc_data:/data
  upload_config:
    build: solrcloud
    image: solrcloud
    command: sh run-solrcloud.sh upload_config
    ports:
    - "127.0.0.1:8983:8983"
    - "127.0.0.1:2181:2181"
    volumes:
    - ./sc_data:/data
